version: '2'
services:
  dev:
    image: keboola/processor-add-filename-column
    tty: true
    stdin_open: true
    volumes:
      - .:/code
      - ./data:/data

  processor-add-filename-column:
    build: .
    image: keboola/processor-add-filename-column
    tty: true
    stdin_open: true

  tests:
    image: keboola/processor-add-filename-column
    tty: true
    stdin_open: true
    volumes:
      - .:/code
    command: php /code/tests/run.php
